### PR TITLE
Reduce error trap leak

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by rustybird** [comment]
`0009-Fix-errorTrap-leak-in-free_win_data.patch` (which accidentally wasn't applied) doesn't look suitable for backporting on top of xfwm 4.14.2, because it uncovers many many unhandled X11 errors that would cause xfwm to abort - unless we also take all the followup fixes:

Even beyond the last [`xfce-4.14` branch](https://gitlab.xfce.org/xfce/xfwm4/-/commits/xfce-4.14) release (xfwm 4.14.6 from 2020), that branch still has 7 unreleased commits matching `myDisplayErrorTrap(Push|Pop)`. And then *even more* from newer branches, after they stopped cherry-picking...

**Comment by marmarek** [comment]
Ouch...
FWIW I do observe the slowdown, after some longer uptime, it's very noticeable on alt-tab (mildly annoying, but not a deal breaker). Crashing window manager indeed is worse (although it should automatically restart, AFAIR).

**Comment by marmarek** [comment]
Anyway, I'll revert https://github.com/QubesOS/qubes-desktop-linux-xfce4-xfwm4/commit/8ce8e770d9eb67ba6fb13663418f321d396dc366 instead

**Comment by rustybird** [comment]
As a disgusting interim improvement, we could remove the second `myDisplayErrorTrapPush()` call in `free_win_data()` (instead of changing it to `myDisplayErrorTrapPopIgnored()` as the 0009 patch does). This way it only leaks error handlers at half the current rate, but the functional behavior should be unchanged.

**Comment by rustybird** [comment]
Commits reordered, and "Fixes" changed to just a mention of the issue

**Comment by rustybird** [comment]
PipelineRetryFailed

**Pull request merged**
